import type { Metadata } from "next";
//import { Montserrat } from "next/font/google";
import "./globals.css";
import { UsersProvider } from "@/providers/UsersContext";
import { montserrat } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const montserrat = Montserrat({
//   weight: ["300", "400", "500", "700", "800"],
//   subsets: ["latin"],
//   display: "swap",
//   fallback: ["Arial", "sans-serif"],
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UsersProvider>
        <body className={`${montserrat.className} antialiased`}>
          {children}
        </body>
      </UsersProvider>
    </html>
  );
}
